### ISSUE TITLE
Swagger Validation Errors

### ISSUE THREAD

**Issue by thallstein** [kinlane/api-evangelist#44]
Hello Kin,

I've been going through the Swagger definitions on http://theapistack.com/just-swagger.html to try find some that I could set up as remote web services on DreamFactory to use as examples. When I paste your Swagger files in to get validated or to import on the swagger.io editor they all turn up some errors. I was wondering if you have an insight as to what might be the case.

Here's an example:

Pasting the file from API Evangelist - http://theapistack.com/data/api-evangelist/api-evangelist-tools-api-swagger.json into http://bigstickcarpet.com/swagger-parser/www/index.html yields the error messages below. Pasting the file into http://editor.swagger.io/#/ via 'Paste JSON' also generates errors. 

I'm sure you're super busy and this is probably user-error on my side, but if you have a suggestion I'm all ears. I'd also love to contribute defining some of the Swagger APIs that you would like to develop / list in your project once I get up to speed.

http://bigstickcarpet.com/swagger-parser/www/index.html OUTPUT =>

Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//tool/{id}/get/parameters/2
    Data does not match any schemas from 'oneOf' at #/paths//tool/{id}/get/parameters/2
      Missing required property: schema at #/
      Data does not match any schemas from 'oneOf' at #/
        No enum match for: path at #/in
        No enum match for: path at #/in
        No enum match for: path at #/in
        Missing required property: required at #/
    Missing required property: $ref at #/paths//tool/{id}/get/parameters/2

JSON_OBJECT_VALIDATION_FAILED

Error: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//tool/{id}/get/parameters/2
    Data does not match any schemas from 'oneOf' at #/paths//tool/{id}/get/parameters/2
      Missing required property: schema at #/
      Data does not match any schemas from 'oneOf' at #/
        No enum match for: path at #/in
        No enum match for: path at #/in
        No enum match for: path at #/in
        Missing required property: required at #/
    Missing required property: $ref at #/paths//tool/{id}/get/parameters/2

JSON_OBJECT_VALIDATION_FAILED
    at http://bigstickcarpet.com/swagger-parser/www/js/bundle.min.js:11:318
    at http://bigstickcarpet.com/swagger-parser/www/js/bundle.min.js:50:316 

SyntaxError: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//tool/{id}/get/parameters/2
    Data does not match any schemas from 'oneOf' at #/paths//tool/{id}/get/parameters/2
      Missing required property: schema at #/
      Data does not match any schemas from 'oneOf' at #/
        No enum match for: path at #/in
        No enum match for: path at #/in
        No enum match for: path at #/in
        Missing required property: required at #/
    Missing required property: $ref at #/paths//tool/{id}/get/parameters/2

JSON_OBJECT_VALIDATION_FAILED
    at Function.syntax (http://bigstickcarpet.com/swagger-parser/dist/swagger-parser.min.js:284:318)
    at validateSchema (http://bigstickcarpet.com/swagger-parser/dist/swagger-parser.min.js:20:254)
    at http://bigstickcarpet.com/swagger-parser/dist/swagger-parser.min.js:8:1921 

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (http://bigstickcarpet.com/swagger-parser/dist/swagger-parser.min.js:2047:3479)
    at validateSchema (http://bigstickcarpet.com/swagger-parser/dist/swagger-parser.min.js:20:158)
    at http://bigstickcarpet.com/swagger-parser/dist/swagger-parser.min.js:8:1921

http://editor.swagger.io/#/ OUTPUT =>

Error
 Object
code:  "ONE_OF_MISSING"
message:  "Not a valid parameter definition"
 path: Array [5]
0:  "paths"
1:  "/tool/{id}"
2:  "get"
3:  "parameters"
4:  "2"
 inner: Array [2]

**Comment by kinlane** [comment]
yeah....my api-stack hasn't been updated in a while...and I'm shifting these documents to be available in my stack.network work, which is next evolution. If you have particular API need, I can point you to as complete enough one as possible....or see if I have more complete on in the master directory. I have other projects where things are more complete - http://stack.apievangelist.com/companies.html  sorry for trouble...I should clean house here.

**Comment by thallstein** [comment]
Gotcha. I'm interested in the Twilio Swagger docs & am having difficulty getting these two to validate:

http://theapistack.com/data/twilio/twilio-messaging-api-swagger.json

http://theapistack.com/data/twilio/twilio-api-swagger.json

Also - if you know of good online tutorials/manuals for learning Swagger I'm poking around (found & have gone through Apiary's and Swagger's specification documentation).

**Comment by kinlane** [comment]
I just added - https://github.com/api-stack/api-stack/blob/gh-pages/data/twilio/complete-openapi-spec.json

**Comment by kinlane** [comment]
Check out the API Handyman. Some of the best walkthroughs out there - https://apihandyman.io/

**Comment by thallstein** [comment]
You're my hero! Thanks for updating the spec & the handyman link.
