### ISSUE TITLE
search and replace http://blog.apievangelist.com by http://apievangelist.com

### ISSUE THREAD

**Issue by hbt** [kinlane/api-evangelist#50]
Many URLs point to http://blog.apievangelist.com and result in an error
removing the "blog." and the URL works. 

Solution:

- create the subdomain to keep old traffic
- run a search and replace on all post files

**Comment by kinlane** [comment]
Thank you for reminding me of this. I've had problems with the page rules on cloudflare....I've put up a temporary solution, until I've fixed 100%. Appreciate you reporting.
