### ISSUE TITLE
Where to find which apis have Swagger files

### ISSUE THREAD

**Issue by colingoldberg** [kinlane/api-evangelist#51]
Hi Kin,

I'm currently on the prowl for sources of Swagger-providing APIs that I want to make available for browsing/importing into Ritc (especially if they are tagged and/or categorized).

Is there somewhere on apievangelist that I can go for this. Human readable is nice, but I am looking for machine-readable.

Thanks

Colin Goldberg

**Comment by kinlane** [comment]
Sorry I never got to this. ;-(
